/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint para comprobar que la api funciona */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catálogo de estaciones de control */
        get: operations["get_estaciones_estaciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estaciones/{codigo_corto}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serie por bloques horarios de una estación
         * @description Bloques (madrugada/manana/tarde/noche) con estadísticos y salida del detector de anomalías, desde `resumen_datos_ml`. Sin fechas, devuelve los últimos 7 días. Interpretar `is_anomaly` solo con `cobertura >= 0.7`.
         */
        get: operations["get_serie_estaciones__codigo_corto__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pregunta en lenguaje natural al asistente */
        post: operations["post_chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Bloque
         * @enum {string}
         */
        Bloque: "madrugada" | "manana" | "tarde" | "noche";
        /**
         * Contaminante
         * @enum {string}
         */
        Contaminante: "NO" | "NO2" | "NOx" | "O3" | "PM10" | "PM2.5";
        /** Estacion */
        Estacion: {
            /** Codigo Corto */
            codigo_corto: number;
            /** Nombre */
            nombre: string;
            /** Direccion */
            direccion: string;
            /** Tipo */
            tipo: string;
            /** Distrito */
            distrito?: string | null;
            /** Latitud */
            latitud?: number | null;
            /** Longitud */
            longitud?: number | null;
            /** Altitud */
            altitud?: number | null;
            /**
             * Contaminantes Medidos
             * @default []
             */
            contaminantes_medidos: string[];
        };
        /**
         * FuenteChat
         * @description De dónde salió la información: consulta SQL o documento del corpus RAG.
         */
        FuenteChat: {
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "sql" | "documento";
            /** Referencia */
            referencia: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PreguntaChat */
        PreguntaChat: {
            /**
             * Pregunta
             * @description Pregunta del usuario en lenguaje natural
             */
            pregunta: string;
        };
        /**
         * PuntoSerie
         * @description Un bloque horario de un día: estadísticos + salida del detector de anomalías.
         */
        PuntoSerie: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /** Bloque */
            bloque: string;
            /** Media */
            media?: number | null;
            /** Maximo */
            maximo?: number | null;
            /** Minimo */
            minimo?: number | null;
            /** N Horas */
            n_horas?: number | null;
            /** Cobertura */
            cobertura?: number | null;
            /** Z Score */
            z_score?: number | null;
            /** Anomaly Score */
            anomaly_score?: number | null;
            /** Is Anomaly */
            is_anomaly?: boolean | null;
        };
        /** RespuestaChat */
        RespuestaChat: {
            /** Respuesta */
            respuesta: string;
            /**
             * Fuentes
             * @default []
             */
            fuentes: components["schemas"]["FuenteChat"][];
            /** Advertencia */
            advertencia?: string | null;
        };
        /** SerieBloques */
        SerieBloques: {
            /** Estacion */
            estacion: number;
            /** Contaminante */
            contaminante: string;
            /**
             * Desde
             * Format: date
             */
            desde: string;
            /**
             * Hasta
             * Format: date
             */
            hasta: string;
            /** Puntos */
            puntos: components["schemas"]["PuntoSerie"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_estaciones_estaciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estacion"][];
                };
            };
        };
    };
    get_serie_estaciones__codigo_corto__series_get: {
        parameters: {
            query: {
                /** @description Uno de los 6 contaminantes objetivo */
                contaminante: components["schemas"]["Contaminante"];
                /** @description Primer día del rango (incluido) */
                desde?: string | null;
                /** @description Último día del rango (incluido); por defecto, hoy */
                hasta?: string | null;
                /** @description Filtrar por un único bloque del día */
                bloque?: components["schemas"]["Bloque"] | null;
            };
            header?: never;
            path: {
                codigo_corto: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerieBloques"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreguntaChat"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaChat"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
